name: Update Words File

on:
  schedule:
    - cron: "0 0 * * *"  # Esegui ogni giorno a mezzanotte UTC
  workflow_dispatch:  # Permette di avviarlo manualmente

jobs:
  update-words:
    permissions:
      contents: write  # Permette il push delle modifiche

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests
          pip install nltk  # Aggiungi questo comando per installare nltk

      - name: Run script
        run: python generate_words.py

      - name: Visualizza il contenuto di keywords.txt
        run: cat keywords.txt  # Stampa il contenuto del file keywords.txt per il debug

      - name: Commit and push changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add keywords.txt
          git commit -m "Aggiornato keywords.txt" || exit 0
          git push
