name: Generate Words and Update File

on:
  schedule:
    - cron: "0 0 * * *"  # Ogni giorno a mezzanotte
  workflow_dispatch:  # Permette l'esecuzione manuale tramite interfaccia GitHub
  push:
    branches:
      - main  # Si esegue su push al ramo principale

jobs:
  update_words_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Pull the latest changes from remote
        run: git pull origin main  # Aggiunto il git pull per risolvere eventuali conflitti

      - name: Run generate_words.py
        run: python generate_words.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Aggiornato words.txt"
          git push origin main  # Dopo il pull, fai il push delle modifiche
